name: Update submodules

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - run: git submodule update --remote

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore(submodules): update submodules [ci skip]" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
